// Given two strings s1 and s2, return true if s2 contains a permutation of s1, or false otherwise.
//In other words, return true if one of s1's permutations is the substring of s2.
/**
 * @param {string} s1
 * @param {string} s2
 * @return {boolean}
 */
 var checkInclusion = function(s1, s2) {
    
};
checkInclusion("ab", "eidbaooo");// TRUE s2 contains one permutation of s1 ("ba").
checkInclusion("ab", "eidboaoo");// FALSE 